plugins_dependencies = %w( vagrant-gatling-rsync vagrant-docker-compose vagrant-vbguest vagrant-docker-login )
plugin_status = false
plugins_dependencies.each do |plugin_name|
  unless Vagrant.has_plugin? plugin_name
    system("vagrant plugin install #{plugin_name}")
    plugin_status = true
    puts " #{plugin_name}  Dependencies installed"
  end
end

# Restart Vagrant if any new plugin installed
if plugin_status === true
  exec "vagrant #{ARGV.join' '}"
else
  puts "All Plugin Dependencies already installed"
end

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-20.04"
  config.vm.define "oncourse"

  # Configurations for Mavhine
  config.vm.provider "virtualbox" do |v|
    v.memory = 4096
    v.cpus = 2
  end

  config.vm.network :private_network, ip: "192.168.10.201"
  config.vm.network "forwarded_port", guest: 80, host: 8081

  # Run all shell commands with these lines:
  config.vm.provision "bootstrap", type: "shell", run: "never", path: './scripts/index.sh'

  config.vm.provision :docker

  # Shared folder
  config.vm.synced_folder "../.", "/home/vagrant"

end